apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnectorContext
metadata:
  # you need one ConfigConnectorContext per namespace
  name: configconnectorcontext.core.cnrm.cloud.google.com
  namespace: config-control
spec:
  googleServiceAccount: "argocd-cloudrun@qwiklabs-gcp-03-d1e800cf070a.iam.gserviceaccount.com"
  stateIntoSpec: Absent